# Generated by Django 4.1.4 on 2023-02-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findmyitem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
